[param]
nombre_sistema = sistema RND (testing)
sucursal = 0
; host = srv1723.hstgr.io
; host = vps-3177145-x.dattaweb.com
host=vps-922868-x.dattaweb.com
; host = notebook-oscar
; basedatos = u604652499_fgpy
basedatos = rnd
; basedatos=fg
; basedatos=conil
InicioSistema = C:\RND\
port = 3306
homo = S
; debug = S
debug = N
icono = vogel_consultoria_oficial.ico
logo = vogel_consultoria_oficial.png
; user = u604652499_fgpy
user = root
; sistema=3
sistema=1
